### ISSUE TITLE
HydePHP v1.0 Launch Preparations 

### ISSUE THREAD

**Issue by caendesilva** [hydephp/develop#1000]
### Tasks

- [x] Post on Twitter
- [x] Create blog post on website
- [x] Update blog post for changed front matter schema [`#1094` (comment)](https://github.com/hydephp/develop/pull/1094#issuecomment-1439642314)

**Comment by caendesilva** [comment]
Breaking out this

- [ ] Publish and document UI Kit package
