### ISSUE TITLE
Source/output directory API/customization improvements tracker

### ISSUE THREAD

**Issue by caendesilva** [hydephp/develop#1008]
### Abstract
There are a few things I want to do to polish up this the source/output directories. Crating this issue to track them.

### Tasks

- [x] https://github.com/hydephp/develop/pull/1007
- [x] https://github.com/hydephp/develop/pull/1014
- [x] https://github.com/hydephp/develop/pull/1015
- [x] https://github.com/hydephp/develop/pull/1016
- [x] https://github.com/hydephp/develop/issues/1010
- [x] https://github.com/hydephp/develop/issues/1009

### Related
- [x] https://github.com/hydephp/develop/pull/1017
- [x] #1018

**Comment by caendesilva** [comment]
Closing as finished as all tasks are implemented.
