### ISSUE TITLE
Router Project Tracker

### ISSUE THREAD

**Issue by caendesilva** [hydephp/develop#178]
## Project Overview

Creating a thread to collect tasks for the router refactoring process.

- [x] https://github.com/hydephp/develop/pull/168
- [x] https://github.com/hydephp/develop/pull/174
- [x] https://github.com/hydephp/develop/pull/182
- [x] https://github.com/hydephp/develop/issues/179
- [x] https://github.com/hydephp/develop/issues/202
- [x] https://github.com/hydephp/develop/issues/183
- [x] https://github.com/hydephp/develop/issues/204
- [x] https://github.com/hydephp/develop/issues/206
- [x] #209
- [x] Do some Router housekeeping, cleaning up the API docs
- [x] Update the autodiscovery docs if needed, _edit: updated navigation docs, think that's all we have currently_

### Abstract

```
Pseudo-Router for Hyde.

This is not a router in the traditional sense that it decides where to go.
Instead, it creates a pre-generated object encapsulating the Hyde autodiscovery.

If successful, this will not only let us emulate Laravel route helpers, but also
serve as the canonical source of truth for the Hyde autodiscovery process.

The routes defined can then also be used to power the RealtimeCompiler without
having to reverse-engineer the source file mapping.

Routes cannot be added manually, instead the route index is created using the
exact same rules as the current autodiscovery process and compiled file output.

The route index shall serve as a multidimensional mapping allowing you to
determine where a source file will be compiled to, and where a compiled
file was generated from.
```

**Comment by caendesilva** [comment]
Would be neat with a Route facade (basically, just class aliasing the route class), and a route() helper method as well?

**Comment by caendesilva** [comment]
As for this <q>Update the autodiscovery docs if needed, edit: updated navigation docs, think that's all we have currently</q>,

We should prob update the autodiscovery section in the architecture concepts. Also, we should note that this is a "pseudo-router". In fact, I think it may be more appropriate to think of it as an abstract syntax tree representing the bridge between the Markdown/Blade/etc source code and the compiled HTML output.

**Comment by caendesilva** [comment]
There is no easy way to change the navigation menu item label for a Blade-based route. We'd either need a config option for that, or add a toRoute helper. I'd like both, if it does not add to much complexity.

**Comment by caendesilva** [comment]
Router has been implemented and all tracked issues are resolved, so will close this for now.
