### ISSUE TITLE
v1.0 Roadmap

### ISSUE THREAD

**Issue by caendesilva** [hydephp/develop#570]
### Abstract

**Preliminary release date HydePHP v1.0 is set to March 14, 2023**, exactly one year after the [Initial Commit](https://github.com/hydephp/hyde/commit/109bddb7b6144ba704e283c220754759276f1a23).

### Feature freeze

Feature freeze will take effect either March 1, or March 7 at the latest, upon which the documentation will be finalized and the backwards compatibility promise will be kicked in. Any remaining planned breaking changes must be resolved before then, as shall any existing deprecated or experimental code.

### Release candidate

The first HydePHP v1.0-RC version will be published tied to the feature freeze. Only bug fixes will be merged during that time frame, barring any critical issue is discovered that needs addressing in a breaking way. This is so that we don't accidentally merge in any unstable code with to little time to fix before the release causing unnecessary delays. 

## Introduction

What do we need for HydePHP version 1.0? What have we done already? Let's talk!

## Tasks

What do we need to get done? Remember, this is a community effort, nothing is yet set in stone, your feedback matters!

### The Really Big Stuff

- [x] #571
- [x] #1064

### The Big Stuff
- [x] https://github.com/hydephp/develop/issues/787
- [x] https://github.com/hydephp/develop/issues/877
- [x] https://github.com/hydephp/develop/issues/939
- [x] #579
- [x] #592

### New Features
- [x] #585
- [x] #880
- [x] #901

### Chores

- [x] #993
- [x] #998
- [x] #999
- [x] #1223
- [x] #1249
- [x] Come up with more things for the roadmap

### Finishing Touches

- [x] #1192
- [x] #1187
- [x] #1186
- [x] #1184
- [x] #1152
- [x] #1193
- [x] #1202
- [x] #1203
- [x] #1206
- [x] #1207

### Originally discussed in https://github.com/hydephp/develop/discussions/569

<div type='discussions-op-text'>

<sup>Originally posted by **caendesilva** October 24, 2022</sup>

**Comment by caendesilva** [comment]
Adding some example sites as text fixtures could be useful to ensure we don't accidentally break BC.

**Comment by caendesilva** [comment]
## Preliminary Release Date: March 14, 2023

Preliminary HydePHP v1.0 is set to March 14, 2023, exactly one year after the [Initial Commit](https://github.com/hydephp/hyde/commit/109bddb7b6144ba704e283c220754759276f1a23).

Feature freeze will take effect either March 1, or March 7.
