### ISSUE TITLE
Separate HydeServiceProvider into multiple providers

### ISSUE THREAD

**Issue by caendesilva** [hydephp/develop#939]
### Abstract

The main HydeServiceProvider class manages a lot of things. Splitting it out to multiple providers, each with their own responsibility domain, will lead to more manageable and modifiable code.

### Tasks

- [x] https://github.com/hydephp/develop/pull/940
- [x] https://github.com/hydephp/develop/pull/942

#### Related

- [x] https://github.com/hydephp/develop/pull/943
- [x] https://github.com/hydephp/develop/pull/944

**Comment by caendesilva** [comment]
Closing as I think it's implemented
