### ISSUE TITLE
Remove experimental code

### ISSUE THREAD

**Issue by caendesilva** [hydephp/develop#998]
### Abstract

Either remove experimental code that should no longer be a part of the package; or refactor them to become stable; or remove markers for code that has now become stable.

### Removed

- [x] DynamicPage.php - This interface is indeed still experimental (Removed in [`#1019`](https://github.com/hydephp/develop/pull/1019))
- [x] InMemoryPage.php - This class is indeed still experimental (Marked stable in [`#1222`](https://github.com/hydephp/develop/pull/1222))

### Resolved
- [x] packages/framework/src/Console/Concerns/Command.php [`#1005`](https://github.com/hydephp/develop/pull/1005)
- [x] packages/framework/src/Framework/Actions/ConvertsMarkdownToPlainText.php [`#1005`](https://github.com/hydephp/develop/pull/1005)
- [x] packages/framework/src/Pages/Concerns/UsesFlattenedOutputPaths.php [`#1005`](https://github.com/hydephp/develop/pull/1005)
- [x] packages/realtime-compiler/src/Http/DashboardController.php [`#1005`](https://github.com/hydephp/develop/pull/1005)
- [x] Config.php - Stable in https://github.com/hydephp/develop/pull/1055

### Documentation entries

Some features in the advanced customization section are classified as experimental, so they probably need another look (when it's not in the middle of the night)

**Comment by caendesilva** [comment]
The following have had their `@experimental` status removed in https://github.com/hydephp/develop/pull/1005

1. Command.php (methods `gray` and `inlineGray`))
   - These methods are unlikely to change at this point 
2. ConvertsMarkdownToPlainText.php (class)
   - Class only has one public method (excluding constructor) so API is unlikely to change
3. UsesFlattenedOutputPaths.php (trait)
   - Trait has not been changed in a long time and is unlikely to do so
4. DashboardController.php (RealtimeCompiler class)
   - The Realtime Compiler package has no backwards compatibility guarantees outside of its coupling with standard HydePHP versions, and thus all of its classes can be considered internal
